import { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./context/authContext";
import { LangProvider } from "./context/langContext";
import { SettingsProvider } from "./context/settingContext";

export const metadata: Metadata = {
  title: "Newspaper",
  description: "Generated by create next NewsPaper",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="bg-gray-200">
        <SettingsProvider>
          <AuthProvider>
            <LangProvider>{children}</LangProvider>
          </AuthProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
