import { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./context/authContext";

export const metadata: Metadata = {
  title: "Newspaper",
  description: "Generated by create next NewsPaper",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className="bg-gray-200">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
